### ISSUE TITLE
Custom id column name

### ISSUE THREAD

**Issue by Idered** [feathersjs/feathers-sequelize#40]
Hey

Service:
```js
const service = require('feathers-sequelize')
const hooks = require('./hooks')

export default function () {
  const app = this
  const models = app.get('sequelize').models

  const options = {
    id: 'uuid',
    Model: models.task
  }

  // Initialize our service with any options it requires
  app.use('/tasks', service(options))

  // Get our initialize service to that we can bind hooks
  const taskService = app.service('/tasks')

  // Set up our before hooks
  taskService.before(hooks.before)

  // Set up our after hooks
  taskService.after(hooks.after)
}
```

Model:
```js
import Sequelize from 'sequelize'

export default function () {
  let sequelize = this.get('sequelize')

  const Task = sequelize.define('task', {
    uuid: {
      type: Sequelize.UUID,
      unique: true,
      isUUID: 4,
      defaultValue: Sequelize.UUIDV4
    },
    userId: {
      type: Sequelize.INTEGER,
      allowNull: false
    },
    workspaceId: {
      type: Sequelize.INTEGER,
      allowNull: false
    },
    content: {
      type: Sequelize.STRING,
      allowNull: false
    },
    isCompleted: {
      type: Sequelize.BOOLEAN,
      defaultValue: 0
    },
    dueDate: {
      type: Sequelize.DATE
    }
  })

  return Task
}
```

The problem:
```
Executing (default): UPDATE `tasks` SET `isCompleted`=false,`updatedAt`='2016-05-17 10:50:49' WHERE `uuid` = 'da136d3f-476d-4ebe-8141-f77b58d9e5c5'
Executing (default): SELECT `id`, `uuid`, `userId`, `workspaceId`, `content`, `isCompleted`, `dueDate`, `createdAt`, `updatedAt` FROM `tasks` AS `task` WHERE `task`.`id` = 'da136d3f-476d-4ebe-8141-f77b58d9e5c5';
```

Patch method after successful update calls getOrFind method. The first query is ok but the second called by getOrFind doesn't use custom id column and generates error.

```
NotFound: No record found for id '88750834-d5a5-42c4-85c0-56ef93616358' at Object.construct (C:\Users\Kasper\Code\ticklist\server\node_modules\core-js\modules\es6.reflect.construct.js:22:24) at NotFound.ExtendableBuiltin (C:\Users\Kasper\Code\ticklist\server\node_modules\feathers-errors\lib\index.js:21:28) at NotFound.FeathersError (C:\Users\Kasper\Code\ticklist\server\node_modules\feathers-errors\lib\index.js:99:87) at new NotFound (C:\Users\Kasper\Code\ticklist\server\node_modules\feathers-errors\lib\index.js:188:77) at [object Object].<anonymous> (C:\Users\Kasper\Code\ticklist\server\node_modules\feathers-sequelize\lib\index.js:106:17) at [object Object].tryCatcher (C:\Users\Kasper\Code\ticklist\server\node_modules\bluebird\js\release\util.js:16:23) at Promise._settlePromiseFromHandler (C:\Users\Kasper\Code\ticklist\server\node_modules\bluebird\js\release\promise.js:502:31) at Promise._settlePromise (C:\Users\Kasper\Code\ticklist\server\node_modules\bluebird\js\release\promise.js:559:18) at Promise._settlePromise0 (C:\Users\Kasper\Code\ticklist\server\node_modules\bluebird\js\release\promise.js:604:10) at Promise._settlePromises (C:\Users\Kasper\Code\ticklist\server\node_modules\bluebird\js\release\promise.js:683:18) at Async._drainQueue (C:\Users\Kasper\Code\ticklist\server\node_modules\bluebird\js\release\async.js:138:16) at Async._drainQueues (C:\Users\Kasper\Code\ticklist\server\node_modules\bluebird\js\release\async.js:148:10) at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Kasper\Code\ticklist\server\node_modules\bluebird\js\release\async.js:17:14) at tryOnImmediate (timers.js:534:15) at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by Idered** [comment]
Ok, found the solution. The custom id name must be defined as primaryKey in model:
```js
import Sequelize from 'sequelize'

export default function () {
  let sequelize = this.get('sequelize')

  const Task = sequelize.define('task', {
    uuid: {
      type: Sequelize.UUID,
      unique: true,
      primaryKey: true,
      isUUID: 4,
      defaultValue: Sequelize.UUIDV4
    },
```
